### ISSUE TITLE
\tag command in pldoc.sty clashes with amsmath package command with the same name

### ISSUE THREAD

**Issue by wvxvw** [SWI-Prolog/packages-pldoc#11]
`\tag` is an important command in `amsmath` package, which, in turn, is almost mandatory for any LaTeX document.  Resolving the clash seems to be beyond simple user's abilities (mine are certainly not enough :).  Would it be possible to rename this command into something else?  More info here: http://tex.stackexchange.com/questions/268597/swi-prolog-documentation-generator-tags-environment-tag-not-allowed

**Comment by JanWielemaker** [comment]
I'm not terribly happy changing this.  It will take considerable time before all generated files are
nicely in sync again with a modified `pldoc.sty` and there isn't any guarantee this will fix such issues forever.  Can't you just include the generated stuff inside a TeX group (`\bgroup` ... `\egroup`) to avoid the conflict?  An alternative might be to scope `\tag` to the `tags` environment.  If you modify pldoc.sty along these lines I'm happy to merge the changes.

**Comment by wvxvw** [comment]
Changing between including the document and inputting the contents with or without wrapping it in `\bgroup .. \egroup` makes no difference in the output for me. Scoping `\tag` to tags environment sounds like a better options, however, I'd still need to learn how to do that :) But I'll see what I can do this evening!

**Comment by francomorando** [comment]
I had the same problem and I modified the Prolog and LaTeX code to get things right. You can find the modified files and some instructions on GitHub in the repository AltPldoc. https://github.com/francomorando/AltPldoc

**Comment by JanWielemaker** [comment]
Had a look at `pldoc.sty`.  IT is really trivial to define the ``\tag`` only in the context of ``\tags``, which should resolve the issue.  Pushed a patch for that.   With the move to CMake the doc building became a lot easier.   everything seems to work and still looks the same.   I assume this fixes the _amsmath_ compatibility without breaking anything, but didn't test.

**Comment by francomorando** [comment]
Thanks Jan for your prompt reply! Actually I have all what I need with that patch so no need to fix this
in a short while! 
Many of my problems were due to clashes with other packages hyperref and graphicx and other definitions I have in my files, this is another story and there is no need to solve this in general.
The point is simply that I started using pldoc at the end of the work and it is a real pain to comply with 
my definitions.
 
On the other hand the clash with amsmath could be of general interest so I tried  the new .sty and got  error:
Illegal parameter number in definition of  \tags here

```
\newcommand{\tag}[1]{\item[#1]}
 \newcommand{\mtag}[1]{\item[#1] \mbox{}\\}}
{\end{description}\end{quote}}
```
	        
this fades away if one says

```
\newcommand{\tag}{\item}
 \newcommand{\mtag}{\item \mbox{}\\}}%
{\end{description}\end{quote}}
```
that obviously is useless but gives some ideas that `#1` cannot be used 
because \tags has no parameters. 
Will try to find a way to escape parameter occurrence to local scope. 

Cheers
 Franco

**Comment by JanWielemaker** [comment]
Odd.  How come this created nice PDF docs!?  One possible way around is to define the ``\tag `` globally with a unique name and use (if I recall correctly) ``\let`` to locally bind `\\tag`` to this global command?

**Comment by JanWielemaker** [comment]
That is easy :+1:   _Seems_ doesn't sound really convinced though ...  Should I wait a little?

**Comment by francomorando** [comment]
This solves the \tag clash for sure, updated my README in my GitHub repo!
This repo  is not so interesting now.  See if you can find of some interest in the particular problems outlined there. 
Thanks 
Franco

**Comment by JanWielemaker** [comment]
Ok.  Updated,  I think we can close this.
