### ISSUE TITLE
Labeled links are not properly generated

### ISSUE THREAD

**Issue by wouterbeek** [SWI-Prolog/packages-pldoc#30]
In the abstract on the [pldoc](http://www.swi-prolog.org/pldoc/doc_for?object=section(%27packages/plunit.html%27)) manual page, the following links are not displayed correctly:

```
\url[SWI-Prolog]{http://www.swi-prolog.org}. The
current version also runs on \url[SICStus
Prolog]{http://www.sics.se/sicstus/}
```

**Comment by JanWielemaker** [comment]
New docs should use the standard `\href{URL}{Label}`.  Updated.

**Comment by wouterbeek** [comment]
@JanWielemaker Where is this syntax documented?  A description of the outdated notation can still be found in `xpce/TeX/html.sty`:

```
%	\email[TextToShow]{URL}
%	\url[TextToShow]{URL}
%
%	References to E-mail addresses and general URL's.  If the optional
%	argument is provided, this is the text printed for the label.  Otherwise
%	the address itself is printed.
```

There are 65 more instances of this notation.  They all lead to bugs in the HTML documentation.

It is easy to fix them all, but my `fill-paragraph` function works different than yours.  What are the parameters on your paragraph filling approach?  I may be able to mimic them in my editor for better consistency.

**Comment by JanWielemaker** [comment]
`\href{URL}{label}` comes from one of the imported packages.  `\url[Label]{URL}` was home brew, either because I missed `\href` or because it did not yet exist.  We're probably talking early nineties ...

I think I prefer a fix by script.  There are far more than I thought.  Pull requests are more likely more rather than less work in this case.

I use M-Q: `justify-paragraph`.  The PceEmacs  language mode refinement first removes line-comment
starts from the lines, justifies and puts them back.  Dunno whether GNU-Emacs can do that as well.
